### ISSUE TITLE
Could you provide sample code for pt to onnx?

### ISSUE THREAD

**Issue by josh3255** [irtrailenium/train-ego-path-detection#2]
thank you for sharing good research.

i want to convert pretrained best.pt to best.onnx and best.engine

could you provide some sample code?

**Comment by GreatTommy** [comment]
Hi @josh3255,

To convert your pretrained `best.pt` model to both ONNX and TensorRT formats, the process is streamlined using the `Detector` class. By simply setting the `runtime` parameter to `tensorrt`, the model will automatically be compiled into TensorRT. You can check out this section of the demo script for an example:

https://github.com/irtrailenium/train-ego-path-detection/blob/bdb0e5f839a577659d20b2f15a5233ec036cea73/demo.py#L77-L86

This conversion is done only once, and it generates a `best.trt` file in the same directory as your weights. This file can be reused for future instances, eliminating the need to reconvert the model.

If you're looking for the ONNX file generated during this process (which is temporary), you can easily retain it by commenting out the line responsible for its deletion. You'll find that here:

https://github.com/irtrailenium/train-ego-path-detection/blob/bdb0e5f839a577659d20b2f15a5233ec036cea73/src/utils/interface.py#L138

Once this line is commented out, you'll be left with a `temp.onnx` file in the root folder, which contains the ONNX model definition you're looking for.

I hope this helps! Feel free to reach out if you have any further questions.

**Comment by SaharGezer** [comment]
When I try to run it with runtime "tensorrt", I did:
model_trt.detect()

I have tried it with tensor which I have created with the transform and I have tried it numpy image but it does not work, I got an error:

when I used numpy image:
    self.cuda.memcpy_htod(self.bindings[0], tensor)  # copy input to GPU
pycuda._driver.LogicError: cuMemcpyHtoD failed: invalid argument

and when I used torch tensor:
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>

how can I solve it?
